version: '2'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - "./conf.d/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./conf.d/redirect.conf:/etc/nginx/conf.d/redirect.conf:ro"
            - "./ssl/www.nalam.me/dhparam.pem:/etc/ssl/www.nalam.me/dhparam.pem:ro"
            - "./ssl/www.nalam.me/gd_bundle-g2-g1.crt:/etc/ssl/www.nalam.me/gd.trusted.crt:ro"
            - "./ssl/www.nalam.me/nalam.key:/etc/ssl/www.nalam.me/privkey.key:ro"
            - "./ssl/www.nalam.me/nalam.me.chained.crt:/etc/ssl/www.nalam.me/cert.crt:ro"
            - "./www:/var/www:ro"
            - "./logs:/var/logs:rw"
